#!/bin/sh

echo "**********************autoGeneratingCode开始**********************"
cd ../
bin/sourcery \
--sources ./RxSample \
--templates ./RxSample/AutoTemplates/Templates/AutoMappable.stencil \
--output ./RxSample/AutoTemplates/Autogenerated
echo "**********************autoGeneratingCode结束**********************"


