#!/bin/sh

echo "**********************autoGeneratingCode开始**********************"
cd ../
Sourcery-0.15.0/bin/sourcery \--sources ./RxSample \
--templates ./RxSample/AutoTemplates/Templates/AutoCodeModel.stencil \
--templates ./RxSample/AutoTemplates/Templates/AutoEquatable.stencil \
--templates ./RxSample/AutoTemplates/Templates/AutoModelToDictionary.stencil \
--templates ./RxSample/AutoTemplates/Templates/AutoCases.stencil \
--templates ./RxSample/AutoTemplates/Templates/AutoDataToModel.stencil \
--output ./RxSample/AutoTemplates/Autogenerated
echo "**********************autoGeneratingCode结束**********************"


