#!/bin/sh

echo "**********************autoGeneratingCode开始**********************"
cd ../
Sourcery-0.15.0/bin/sourcery \
--sources ./RxSample \
--templates ./RxSample/AutoTemplates/Templates/AutoMappable.stencil \
--output ./RxSample/AutoTemplates/Autogenerated
echo "**********************autoGeneratingCode结束**********************"


